# Generated by Django 5.2.3 on 2025-07-19 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalwarehouse',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Warehouse', 'verbose_name_plural': 'historical Warehouses'},
        ),
        migrations.AlterModelOptions(
            name='warehouse',
            options={'ordering': ['name'], 'verbose_name': 'Warehouse', 'verbose_name_plural': 'Warehouses'},
        ),
        migrations.AddField(
            model_name='historicalwarehouse',
            name='code',
            field=models.CharField(db_index=True, default='WH001', help_text='Unique warehouse code (2-10 alphanumeric characters)', max_length=10),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='code',
            field=models.CharField(default='WH001', help_text='Unique warehouse code (2-10 alphanumeric characters)', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='historicalwarehouse',
            name='address',
            field=models.TextField(blank=True, help_text='Physical address of the warehouse', null=True),
        ),
        migrations.AlterField(
            model_name='historicalwarehouse',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp when record was created'),
        ),
        migrations.AlterField(
            model_name='historicalwarehouse',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalwarehouse',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this record is active and can be used'),
        ),
        migrations.AlterField(
            model_name='historicalwarehouse',
            name='name',
            field=models.CharField(help_text='Warehouse display name', max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalwarehouse',
            name='note',
            field=models.TextField(blank=True, help_text='Additional notes about the warehouse', null=True),
        ),
        migrations.AlterField(
            model_name='historicalwarehouse',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp when record was last updated'),
        ),
        migrations.AlterField(
            model_name='historicalwarehouse',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalwarehouse',
            name='version',
            field=models.PositiveIntegerField(default=1, help_text='Version number for optimistic locking'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='address',
            field=models.TextField(blank=True, help_text='Physical address of the warehouse', null=True),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when record was created'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='created_by',
            field=models.ForeignKey(help_text='User who created this record', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this record is active and can be used'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='name',
            field=models.CharField(help_text='Warehouse display name', max_length=100),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='note',
            field=models.TextField(blank=True, help_text='Additional notes about the warehouse', null=True),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='updated_by',
            field=models.ForeignKey(help_text='User who last updated this record', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='version',
            field=models.PositiveIntegerField(default=1, help_text='Version number for optimistic locking'),
        ),
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(fields=['name'], name='inventory_w_name_703b74_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(fields=['code'], name='inventory_w_code_2cdc02_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(fields=['is_active'], name='inventory_w_is_acti_3ddeac_idx'),
        ),
    ]
