# Generated by Django 5.2.3 on 2025-07-21 06:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_add_warehouse_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalstockmovement',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Stock Movement', 'verbose_name_plural': 'historical Stock Movements'},
        ),
        migrations.AlterModelOptions(
            name='stockmovement',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'Stock Movement', 'verbose_name_plural': 'Stock Movements'},
        ),
        migrations.AlterField(
            model_name='historicalstockmovement',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp when record was created'),
        ),
        migrations.AlterField(
            model_name='historicalstockmovement',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalstockmovement',
            name='note',
            field=models.TextField(blank=True, help_text='Additional notes about this stock movement', null=True),
        ),
        migrations.AlterField(
            model_name='historicalstockmovement',
            name='reference_id',
            field=models.IntegerField(blank=True, help_text='ID of the referenced document', null=True),
        ),
        migrations.AlterField(
            model_name='historicalstockmovement',
            name='reference_type',
            field=models.CharField(choices=[('NONE', 'None'), ('ADJUST', 'Adjust'), ('PACKING_LIST', 'Packing List'), ('PRODUCTION', 'Production'), ('INVOICE', 'Invoice')], default='NONE', help_text='Type of document this movement references', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalstockmovement',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('CONFIRMED', 'Confirmed')], default='DRAFT', help_text='Current status of the stock movement', max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalstockmovement',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp when record was last updated'),
        ),
        migrations.AlterField(
            model_name='historicalstockmovement',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalstockmovement',
            name='version',
            field=models.PositiveIntegerField(default=1, help_text='Version number for optimistic locking'),
        ),
        migrations.AlterField(
            model_name='historicalstockmovement',
            name='warehouse',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Warehouse where this stock movement occurs', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.warehouse'),
        ),
        migrations.AlterField(
            model_name='historicalwarehouse',
            name='code',
            field=models.CharField(db_index=True, help_text='Unique warehouse code (2-10 alphanumeric characters)', max_length=10),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when record was created'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='created_by',
            field=models.ForeignKey(help_text='User who created this record', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='note',
            field=models.TextField(blank=True, help_text='Additional notes about this stock movement', null=True),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='reference_id',
            field=models.IntegerField(blank=True, help_text='ID of the referenced document', null=True),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='reference_type',
            field=models.CharField(choices=[('NONE', 'None'), ('ADJUST', 'Adjust'), ('PACKING_LIST', 'Packing List'), ('PRODUCTION', 'Production'), ('INVOICE', 'Invoice')], default='NONE', help_text='Type of document this movement references', max_length=20),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('CONFIRMED', 'Confirmed')], default='DRAFT', help_text='Current status of the stock movement', max_length=10),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='updated_by',
            field=models.ForeignKey(help_text='User who last updated this record', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='version',
            field=models.PositiveIntegerField(default=1, help_text='Version number for optimistic locking'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='warehouse',
            field=models.ForeignKey(help_text='Warehouse where this stock movement occurs', on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='inventory.warehouse'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='code',
            field=models.CharField(help_text='Unique warehouse code (2-10 alphanumeric characters)', max_length=10, unique=True),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['warehouse', 'status'], name='inventory_s_warehou_d175bf_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['reference_type', 'reference_id'], name='inventory_s_referen_85b37c_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['created_at'], name='inventory_s_created_b4ad8a_idx'),
        ),
        migrations.AlterModelTable(
            name='stockmovement',
            table='inventory_stock_movement',
        ),
    ]
