# Generated by Django 5.2.3 on 2025-09-11 04:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_create_warehouse_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='stockmovement',
            name='unique_draft_per_warehouse',
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'DRAFT')), fields=('warehouse', 'reference_type', 'reference_id'), name='unique_draft_per_reference'),
        ),
    ]
