# Generated by Django 5.2.3 on 2025-07-21 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_historicalstockmovement_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='stockmovementitem',
            new_name='inventory_s_stock_m_21363d_idx',
            old_name='inventory_s_stock_m_2f5cf8_idx',
        ),
        migrations.RenameIndex(
            model_name='stockmovementitem',
            new_name='inventory_s_movemen_2c0e34_idx',
            old_name='inventory_s_movemen_28876d_idx',
        ),
        migrations.RenameIndex(
            model_name='stockmovementitem',
            new_name='inventory_s_lot_num_5e9ff6_idx',
            old_name='inventory_s_lot_num_0c0fb7_idx',
        ),
        migrations.AlterField(
            model_name='historicalstockmovementitem',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp when record was created'),
        ),
        migrations.AlterField(
            model_name='historicalstockmovementitem',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalstockmovementitem',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp when record was last updated'),
        ),
        migrations.AlterField(
            model_name='historicalstockmovementitem',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalstockmovementitem',
            name='version',
            field=models.PositiveIntegerField(default=1, help_text='Version number for optimistic locking'),
        ),
        migrations.AlterField(
            model_name='stockmovementitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when record was created'),
        ),
        migrations.AlterField(
            model_name='stockmovementitem',
            name='created_by',
            field=models.ForeignKey(help_text='User who created this record', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stockmovementitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated'),
        ),
        migrations.AlterField(
            model_name='stockmovementitem',
            name='updated_by',
            field=models.ForeignKey(help_text='User who last updated this record', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stockmovementitem',
            name='version',
            field=models.PositiveIntegerField(default=1, help_text='Version number for optimistic locking'),
        ),
        migrations.AlterModelTable(
            name='stockmovementitem',
            table='inventory_stock_movement_item',
        ),
    ]
