# Generated by Django 5.2.3 on 2025-07-09 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_stockmovement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockmovement',
            name='movement_type',
        ),
    ]
