# Generated by Django 5.2.3 on 2025-07-23 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_rename_inventory_s_stock_m_2f5cf8_idx_inventory_s_stock_m_21363d_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalstockmovementitem',
            name='lot_number',
            field=models.CharField(default=1, help_text='Lot or batch number for traceability', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stockmovementitem',
            name='lot_number',
            field=models.CharField(default=1, help_text='Lot or batch number for traceability', max_length=64),
            preserve_default=False,
        ),
    ]
