# Generated by Django 5.2.3 on 2025-09-24 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_update_stock_movement_constraints'),
    ]

    operations = [
        # Check if the material_reservation table exists and create if not
        migrations.RunSQL(
            "CREATE TABLE IF NOT EXISTS inventory_material_reservation ("
            "id INTEGER PRIMARY KEY AUTOINCREMENT, "
            "created_at DATETIME NOT NULL, "
            "updated_at DATETIME NOT NULL, "
            "version INTEGER NOT NULL DEFAULT 1, "
            "reference_type VARCHAR(30) NOT NULL, "
            "reference_id INTEGER NOT NULL, "
            "reserved_quantity DECIMAL(12,3) NOT NULL, "
            "status VARCHAR(20) NOT NULL DEFAULT 'RESERVED', "
            "item_sku_id BIGINT NOT NULL REFERENCES catalog_itemsku(id), "
            "warehouse_id BIGINT NOT NULL REFERENCES inventory_warehouse(id), "
            "created_by_id INTEGER NOT NULL REFERENCES auth_user(id), "
            "updated_by_id INTEGER NOT NULL REFERENCES auth_user(id)"
            ");",
            reverse_sql="DROP TABLE IF EXISTS inventory_material_reservation;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_material_reservation_ref ON inventory_material_reservation(reference_type, reference_id);",
            reverse_sql="DROP INDEX IF EXISTS idx_material_reservation_ref;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_material_reservation_item ON inventory_material_reservation(item_sku_id);",
            reverse_sql="DROP INDEX IF EXISTS idx_material_reservation_item;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_material_reservation_warehouse ON inventory_material_reservation(warehouse_id);",
            reverse_sql="DROP INDEX IF EXISTS idx_material_reservation_warehouse;"
        ),
    ]
