# Generated by Django 5.2.3 on 2025-07-30 05:36

import common.mixins.validatable
import django.db.models.deletion
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_create_stock_model'),
        ('inventory', '0005_make_lot_number_required'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalstockmovement',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('CONFIRMED', 'Confirmed'), ('PROCESSING', 'Processing Stock Changes'), ('COMPLETED', 'Stock Changes Completed'), ('FAILED', 'Stock Processing Failed')], default='DRAFT', help_text='Current status of the stock movement', max_length=10),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('CONFIRMED', 'Confirmed'), ('PROCESSING', 'Processing Stock Changes'), ('COMPLETED', 'Stock Changes Completed'), ('FAILED', 'Stock Processing Failed')], default='DRAFT', help_text='Current status of the stock movement', max_length=10),
        ),
        migrations.CreateModel(
            name='HistoricalStock',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, help_text='Timestamp when record was last updated')),
                ('version', models.PositiveIntegerField(default=1, help_text='Version number for optimistic locking')),
                ('lot_number', models.CharField(help_text='Lot number for tracking and traceability', max_length=50)),
                ('expiry_date', models.DateField(help_text='Expiry date for FEFO (First Expired, First Out) logic')),
                ('available_quantity', models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Available quantity in stock', max_digits=10)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('item_sku', models.ForeignKey(blank=True, db_constraint=False, help_text='Item SKU for this stock record', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalog.itemsku')),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(blank=True, db_constraint=False, help_text='Warehouse where stock is located', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.warehouse')),
            ],
            options={
                'verbose_name': 'historical Stock',
                'verbose_name_plural': 'historical Stocks',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('version', models.PositiveIntegerField(default=1, help_text='Version number for optimistic locking')),
                ('lot_number', models.CharField(help_text='Lot number for tracking and traceability', max_length=50)),
                ('expiry_date', models.DateField(help_text='Expiry date for FEFO (First Expired, First Out) logic')),
                ('available_quantity', models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Available quantity in stock', max_digits=10)),
                ('created_by', models.ForeignKey(help_text='User who created this record', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('item_sku', models.ForeignKey(help_text='Item SKU for this stock record', on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='catalog.itemsku')),
                ('updated_by', models.ForeignKey(help_text='User who last updated this record', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(help_text='Warehouse where stock is located', on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='inventory.warehouse')),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stocks',
                'db_table': 'inventory_stock',
                'ordering': ['warehouse', 'item_sku', 'expiry_date', 'lot_number'],
                'indexes': [models.Index(fields=['item_sku', 'warehouse', 'expiry_date'], name='inventory_s_item_sk_392ad3_idx'), models.Index(fields=['item_sku', 'warehouse', 'lot_number'], name='inventory_s_item_sk_06675a_idx'), models.Index(fields=['warehouse', 'item_sku'], name='inventory_s_warehou_af2571_idx'), models.Index(fields=['expiry_date'], name='inventory_s_expiry__b1d30a_idx')],
                'constraints': [models.UniqueConstraint(fields=('item_sku', 'warehouse', 'lot_number', 'expiry_date'), name='unique_stock_record'), models.CheckConstraint(condition=models.Q(('available_quantity__gte', 0)), name='positive_available_quantity')],
            },
            bases=(common.mixins.validatable.ValidatableMixin, models.Model),
        ),
    ]
