# Generated by Django 5.2.3 on 2025-09-24 03:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20250924_1000'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='stockmovement',
            name='unique_draft_per_warehouse_reference',
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'DRAFT'), models.Q(('reference_type__in', ['NONE', 'ADJUST']), _negated=True)), fields=('warehouse', 'reference_type', 'reference_id'), name='unique_draft_per_warehouse_reference'),
        ),
    ]
