# Generated by Django 5.2.3 on 2025-07-11 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_bom_historicalbom'),
        ('inventory', '0005_historicalstockmovement_stockmovement_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovementItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('IN', 'IN'), ('OUT', 'OUT')], max_length=3)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('lot', models.CharField(blank=True, max_length=64, null=True)),
                ('expired', models.DateField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.itemsku')),
                ('stock_movement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.stockmovement')),
            ],
            options={
                'verbose_name': 'Stock Movement Item',
                'verbose_name_plural': 'Stock Movement Items',
                'unique_together': {('stock_movement', 'item', 'lot', 'movement_type')},
            },
        ),
    ]
