# Generated by Django 5.2.3 on 2025-09-24 03:24

from django.conf import settings
from django.db import migrations, models


def convert_none_to_adjust(apps, schema_editor):
    """Convert existing NONE reference types to ADJUST"""
    StockMovement = apps.get_model('inventory', 'StockMovement')
    StockMovement.objects.filter(reference_type='NONE').update(reference_type='ADJUST')
    
    # Also update historical records if they exist
    try:
        HistoricalStockMovement = apps.get_model('inventory', 'HistoricalStockMovement')
        HistoricalStockMovement.objects.filter(reference_type='NONE').update(reference_type='ADJUST')
    except LookupError:
        # Historical model doesn't exist, skip
        pass


def reverse_convert_adjust_to_none(apps, schema_editor):
    """Reverse migration: Convert ADJUST back to NONE"""
    StockMovement = apps.get_model('inventory', 'StockMovement')
    # Only convert ADJUST records that have no reference_id back to NONE
    StockMovement.objects.filter(reference_type='ADJUST', reference_id__isnull=True).update(reference_type='NONE')
    
    # Also update historical records if they exist
    try:
        HistoricalStockMovement = apps.get_model('inventory', 'HistoricalStockMovement')
        HistoricalStockMovement.objects.filter(reference_type='ADJUST', reference_id__isnull=True).update(reference_type='NONE')
    except LookupError:
        # Historical model doesn't exist, skip
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_update_adjust_reference_behavior'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='stockmovement',
            name='unique_draft_per_warehouse_reference',
        ),
        # Convert existing NONE records to ADJUST before changing field choices
        migrations.RunPython(
            convert_none_to_adjust,
            reverse_convert_adjust_to_none,
        ),
        migrations.AlterField(
            model_name='historicalstockmovement',
            name='reference_type',
            field=models.CharField(choices=[('ADJUST', 'Adjust'), ('INBOUND', 'Inbound'), ('OUTBOUND', 'Outbound'), ('PRODUCTION', 'Production')], default='ADJUST', help_text='Type of document this movement references', max_length=20),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='reference_type',
            field=models.CharField(choices=[('ADJUST', 'Adjust'), ('INBOUND', 'Inbound'), ('OUTBOUND', 'Outbound'), ('PRODUCTION', 'Production')], default='ADJUST', help_text='Type of document this movement references', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'DRAFT'), models.Q(('reference_type__in', ['ADJUST', 'INBOUND', 'OUTBOUND']), _negated=True)), fields=('warehouse', 'reference_type', 'reference_id'), name='unique_draft_per_warehouse_reference'),
        ),
    ]
