# Generated by Django 5.2.3 on 2025-08-01 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_create_stock_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalstock',
            name='expiry_date',
            field=models.DateField(blank=True, help_text='Expiry date for FEFO (First Expired, First Out) logic', null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='expiry_date',
            field=models.DateField(blank=True, help_text='Expiry date for FEFO (First Expired, First Out) logic', null=True),
        ),
    ]
