# Generated by Django 5.2.3 on 2025-08-07 04:43

import common.mixins.validatable
import django.core.validators
import django.db.models.deletion
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_refactor_bom_with_mixins'),
        ('inventory', '0007_allow_null_expiry_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalStockAlert',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, help_text='Timestamp when record was last updated')),
                ('version', models.PositiveIntegerField(default=1, help_text='Version number for optimistic locking')),
                ('minimum_threshold', models.DecimalField(decimal_places=2, help_text='Minimum stock level that triggers a warning alert', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('critical_threshold', models.DecimalField(decimal_places=2, help_text='Critical stock level that triggers an urgent alert', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('is_enabled', models.BooleanField(default=True, help_text='Whether this alert is active')),
                ('note', models.TextField(blank=True, help_text='Additional notes about this alert configuration', null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('item_sku', models.ForeignKey(blank=True, db_constraint=False, help_text='The item SKU for this alert', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalog.itemsku')),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(blank=True, db_constraint=False, help_text='The warehouse for this alert', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.warehouse')),
            ],
            options={
                'verbose_name': 'historical Stock Alert',
                'verbose_name_plural': 'historical Stock Alerts',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='StockAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('version', models.PositiveIntegerField(default=1, help_text='Version number for optimistic locking')),
                ('minimum_threshold', models.DecimalField(decimal_places=2, help_text='Minimum stock level that triggers a warning alert', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('critical_threshold', models.DecimalField(decimal_places=2, help_text='Critical stock level that triggers an urgent alert', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('is_enabled', models.BooleanField(default=True, help_text='Whether this alert is active')),
                ('note', models.TextField(blank=True, help_text='Additional notes about this alert configuration', null=True)),
                ('created_by', models.ForeignKey(help_text='User who created this record', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('item_sku', models.ForeignKey(help_text='The item SKU for this alert', on_delete=django.db.models.deletion.CASCADE, related_name='stock_alerts', to='catalog.itemsku')),
                ('updated_by', models.ForeignKey(help_text='User who last updated this record', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(help_text='The warehouse for this alert', on_delete=django.db.models.deletion.CASCADE, related_name='stock_alerts', to='inventory.warehouse')),
            ],
            options={
                'verbose_name': 'Stock Alert',
                'verbose_name_plural': 'Stock Alerts',
                'db_table': 'inventory_stock_alert',
                'indexes': [models.Index(fields=['item_sku'], name='idx_stock_alert_item'), models.Index(fields=['warehouse'], name='idx_stock_alert_warehouse'), models.Index(fields=['is_enabled'], name='idx_stock_alert_enabled')],
                'unique_together': {('item_sku', 'warehouse')},
            },
            bases=(common.mixins.validatable.ValidatableMixin, models.Model),
        ),
    ]
