# Generated by Django 5.2.3 on 2025-09-24 04:32

import common.mixins.validatable
import django.db.models.deletion
import inventory.models.stock_movement_image
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_update_reference_types'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalStockMovementImage',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, help_text='Timestamp when record was last updated')),
                ('version', models.PositiveIntegerField(default=1, help_text='Version number for optimistic locking')),
                ('image', models.TextField(help_text='Document image file for the stock movement', max_length=100)),
                ('caption', models.CharField(blank=True, default='', help_text="Optional caption describing the document (e.g., 'Receipt', 'Delivery Note')", max_length=255)),
                ('is_primary', models.BooleanField(default=False, help_text='Mark as primary document image for the stock movement')),
                ('note', models.TextField(blank=True, default='', help_text='Additional notes about the document or image')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('stock_movement', models.ForeignKey(blank=True, db_constraint=False, help_text='The stock movement this image belongs to', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.stockmovement')),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Stock Movement Image',
                'verbose_name_plural': 'historical Stock Movement Images',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='StockMovementImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('version', models.PositiveIntegerField(default=1, help_text='Version number for optimistic locking')),
                ('image', models.ImageField(help_text='Document image file for the stock movement', upload_to=inventory.models.stock_movement_image.upload_stock_movement_image_path)),
                ('caption', models.CharField(blank=True, default='', help_text="Optional caption describing the document (e.g., 'Receipt', 'Delivery Note')", max_length=255)),
                ('is_primary', models.BooleanField(default=False, help_text='Mark as primary document image for the stock movement')),
                ('note', models.TextField(blank=True, default='', help_text='Additional notes about the document or image')),
                ('created_by', models.ForeignKey(help_text='User who created this record', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('stock_movement', models.ForeignKey(help_text='The stock movement this image belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='inventory.stockmovement')),
                ('updated_by', models.ForeignKey(help_text='User who last updated this record', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stock Movement Image',
                'verbose_name_plural': 'Stock Movement Images',
                'db_table': 'inventory_stockmovementimage',
                'ordering': ['-is_primary', '-created_at'],
                'indexes': [models.Index(fields=['stock_movement'], name='inventory_s_stock_m_5b5b20_idx'), models.Index(fields=['is_primary'], name='inventory_s_is_prim_ca2585_idx'), models.Index(fields=['created_at'], name='inventory_s_created_b8c33c_idx')],
            },
            bases=(common.mixins.validatable.ValidatableMixin, models.Model),
        ),
    ]
