# Generated by Django 5.2.3 on 2025-09-24 06:27

import inventory.models.stock_movement_image
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_add_stock_movement_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalstockmovementimage',
            name='image',
            field=models.TextField(help_text='Document image or PDF file for the stock movement', max_length=100),
        ),
        migrations.AlterField(
            model_name='stockmovementimage',
            name='image',
            field=models.FileField(help_text='Document image or PDF file for the stock movement', upload_to=inventory.models.stock_movement_image.upload_stock_movement_image_path),
        ),
    ]
