# Generated by Django 5.2.3 on 2025-08-26 04:02

import common.mixins.validatable
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_remove_itemimage_unique_primary_image_per_item'),
        ('inventory', '0008_historicalstockalert_stockalert'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalMaterialReservation',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, help_text='Timestamp when record was last updated')),
                ('version', models.PositiveIntegerField(default=1, help_text='Version number for optimistic locking')),
                ('reference_type', models.CharField(choices=[('PRODUCTION', 'Production Order'), ('SALES', 'Sales Order')], help_text='Context ของการจอง เช่น PRODUCTION, SALES', max_length=30)),
                ('reference_id', models.PositiveIntegerField(help_text='ID ของ reference เช่น production_order_id, sales_order_id')),
                ('reserved_quantity', models.DecimalField(decimal_places=3, help_text='จำนวนที่จอง', max_digits=12)),
                ('status', models.CharField(choices=[('RESERVED', 'Reserved'), ('RELEASED', 'Released'), ('COMMITTED', 'Committed'), ('CANCELLED', 'Cancelled')], default='RESERVED', help_text='สถานะการจอง', max_length=20)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('item_sku', models.ForeignKey(blank=True, db_constraint=False, help_text='Item SKU ที่จอง', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalog.itemsku')),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(blank=True, db_constraint=False, help_text='คลังที่จองวัสดุ', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.warehouse')),
            ],
            options={
                'verbose_name': 'historical Material Reservation',
                'verbose_name_plural': 'historical Material Reservations',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='MaterialReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('version', models.PositiveIntegerField(default=1, help_text='Version number for optimistic locking')),
                ('reference_type', models.CharField(choices=[('PRODUCTION', 'Production Order'), ('SALES', 'Sales Order')], help_text='Context ของการจอง เช่น PRODUCTION, SALES', max_length=30)),
                ('reference_id', models.PositiveIntegerField(help_text='ID ของ reference เช่น production_order_id, sales_order_id')),
                ('reserved_quantity', models.DecimalField(decimal_places=3, help_text='จำนวนที่จอง', max_digits=12)),
                ('status', models.CharField(choices=[('RESERVED', 'Reserved'), ('RELEASED', 'Released'), ('COMMITTED', 'Committed'), ('CANCELLED', 'Cancelled')], default='RESERVED', help_text='สถานะการจอง', max_length=20)),
                ('created_by', models.ForeignKey(help_text='User who created this record', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('item_sku', models.ForeignKey(help_text='Item SKU ที่จอง', on_delete=django.db.models.deletion.PROTECT, related_name='material_reservations', to='catalog.itemsku')),
                ('updated_by', models.ForeignKey(help_text='User who last updated this record', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(help_text='คลังที่จองวัสดุ', on_delete=django.db.models.deletion.PROTECT, related_name='material_reservations', to='inventory.warehouse')),
            ],
            options={
                'verbose_name': 'Material Reservation',
                'verbose_name_plural': 'Material Reservations',
                'db_table': 'material_reservation',
                'indexes': [models.Index(fields=['reference_type', 'reference_id'], name='material_re_referen_8e2c4e_idx'), models.Index(fields=['item_sku'], name='material_re_item_sk_0376d4_idx'), models.Index(fields=['warehouse'], name='material_re_warehou_b66971_idx')],
            },
            bases=(common.mixins.validatable.ValidatableMixin, models.Model),
        ),
    ]
