# Generated by Django 5.2.3 on 2025-08-27 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_remove_itemimage_unique_primary_image_per_item'),
        ('inventory', '0009_historicalmaterialreservation_materialreservation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='materialreservation',
            unique_together={('reference_type', 'reference_id', 'item_sku', 'warehouse')},
        ),
    ]
