# Generated by Django 5.2.3 on 2025-08-27 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_materialreservation_unique_together'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='materialreservation',
            new_name='inventory_m_referen_2b7048_idx',
            old_name='material_re_referen_8e2c4e_idx',
        ),
        migrations.RenameIndex(
            model_name='materialreservation',
            new_name='inventory_m_item_sk_1b1b53_idx',
            old_name='material_re_item_sk_0376d4_idx',
        ),
        migrations.RenameIndex(
            model_name='materialreservation',
            new_name='inventory_m_warehou_ed0e42_idx',
            old_name='material_re_warehou_b66971_idx',
        ),
        migrations.AlterModelTable(
            name='materialreservation',
            table='inventory_material_reservation',
        ),
    ]
