# Generated by Django 5.2.3 on 2025-08-20 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalproductionorder',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='productionorder',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='historicalproductionorder',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('CREATED', 'Created'), ('IN_PROGRESS', 'In Progress'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', help_text='Current status of the production order', max_length=20),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('CREATED', 'Created'), ('IN_PROGRESS', 'In Progress'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', help_text='Current status of the production order', max_length=20),
        ),
    ]
