# Generated by Django 5.2.3 on 2025-09-05 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproductionresult',
            name='note',
            field=models.TextField(blank=True, default='', help_text='หมายเหตุเพิ่มเติมเกี่ยวกับกระบวนการผลิต'),
        ),
        migrations.AddField(
            model_name='productionresult',
            name='note',
            field=models.TextField(blank=True, default='', help_text='หมายเหตุเพิ่มเติมเกี่ยวกับกระบวนการผลิต'),
        ),
    ]
