# Generated by Django 5.2.3 on 2025-08-21 03:23

import common.mixins.validatable
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_remove_itemimage_unique_primary_image_per_item'),
        ('production', '0002_remove_historicalproductionorder_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalProductionOrderBOM',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, help_text='Timestamp when record was last updated')),
                ('version', models.PositiveIntegerField(default=1, help_text='Version number for optimistic locking')),
                ('planned_quantity', models.DecimalField(decimal_places=2, help_text='Planned quantity to produce', max_digits=12)),
                ('note', models.TextField(blank=True, default='')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('item_sku', models.ForeignKey(blank=True, db_constraint=False, help_text='ItemSKU to be produced by this BOM', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalog.itemsku')),
                ('production_order', models.ForeignKey(blank=True, db_constraint=False, help_text='Production order this BOM belongs to', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='production.productionorder')),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Production Order BOM',
                'verbose_name_plural': 'historical Production Order BOMs',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ProductionOrderBOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('version', models.PositiveIntegerField(default=1, help_text='Version number for optimistic locking')),
                ('planned_quantity', models.DecimalField(decimal_places=2, help_text='Planned quantity to produce', max_digits=12)),
                ('note', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(help_text='User who created this record', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('item_sku', models.ForeignKey(help_text='ItemSKU to be produced by this BOM', on_delete=django.db.models.deletion.PROTECT, to='catalog.itemsku')),
                ('production_order', models.ForeignKey(help_text='Production order this BOM belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='boms', to='production.productionorder')),
                ('updated_by', models.ForeignKey(help_text='User who last updated this record', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Production Order BOM',
                'verbose_name_plural': 'Production Order BOMs',
                'db_table': 'production_order_bom',
                'indexes': [models.Index(fields=['production_order'], name='production__product_57da0a_idx'), models.Index(fields=['item_sku'], name='production__item_sk_89d245_idx')],
                'constraints': [models.UniqueConstraint(fields=('production_order', 'item_sku'), name='unique_bom_item')],
            },
            bases=(common.mixins.validatable.ValidatableMixin, models.Model),
        ),
    ]
