# Generated by Django 5.2.3 on 2025-09-10 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_historicalproductionresult_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproductionorder',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('CREATED', 'Created'), ('IN_PROGRESS', 'In Progress'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('CLOSED_COMPLETED', 'Closed (Completed)'), ('CLOSED_CANCELLED', 'Closed (Cancelled)')], default='DRAFT', help_text='Current status of the production order', max_length=20),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('CREATED', 'Created'), ('IN_PROGRESS', 'In Progress'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('CLOSED_COMPLETED', 'Closed (Completed)'), ('CLOSED_CANCELLED', 'Closed (Cancelled)')], default='DRAFT', help_text='Current status of the production order', max_length=20),
        ),
    ]
