# Generated by Django 5.2.3 on 2025-09-05 06:44

import catalog.models.image
import common.mixins.validatable
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('version', models.PositiveIntegerField(default=1, help_text='Version number for optimistic locking')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this record is active and can be used')),
                ('name', models.CharField(help_text='Category display name', max_length=100, unique=True)),
                ('note', models.TextField(blank=True, default='', help_text='Optional note about the category')),
                ('created_by', models.ForeignKey(help_text='User who created this record', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(help_text='User who last updated this record', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'catalog_category',
                'ordering': ['name'],
            },
            bases=(common.mixins.validatable.ValidatableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalCategory',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, help_text='Timestamp when record was last updated')),
                ('version', models.PositiveIntegerField(default=1, help_text='Version number for optimistic locking')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this record is active and can be used')),
                ('name', models.CharField(db_index=True, help_text='Category display name', max_length=100)),
                ('note', models.TextField(blank=True, default='', help_text='Optional note about the category')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Category',
                'verbose_name_plural': 'historical Categories',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalItemSKU',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, help_text='Timestamp when record was last updated')),
                ('version', models.PositiveIntegerField(default=1, help_text='Version number for optimistic locking')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('DRAFT', 'Draft')], default='ACTIVE', help_text='Current status of the item - DRAFT allows BOM structure changes, ACTIVE/INACTIVE locks BOM structure', max_length=20)),
                ('sku_code', models.CharField(db_index=True, help_text='Unique identifier for the item', max_length=50)),
                ('name', models.CharField(help_text='Display name for the item', max_length=100)),
                ('unit', models.CharField(help_text="Unit of measurement (e.g., 'pcs', 'kg', 'liters')", max_length=20)),
                ('type', models.CharField(choices=[('RAW', 'Raw Material'), ('PRODUCT', 'Finished Product'), ('PACKAGE', 'Package')], default='RAW', help_text='Type of item - cannot be changed once set', max_length=20)),
                ('note', models.TextField(blank=True, default='', help_text='Additional notes about the item')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('category', models.ForeignKey(blank=True, db_constraint=False, help_text='Category this item belongs to', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalog.category')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Item SKU',
                'verbose_name_plural': 'historical Item SKUs',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ItemSKU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('version', models.PositiveIntegerField(default=1, help_text='Version number for optimistic locking')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('DRAFT', 'Draft')], default='ACTIVE', help_text='Current status of the item - DRAFT allows BOM structure changes, ACTIVE/INACTIVE locks BOM structure', max_length=20)),
                ('sku_code', models.CharField(help_text='Unique identifier for the item', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Display name for the item', max_length=100)),
                ('unit', models.CharField(help_text="Unit of measurement (e.g., 'pcs', 'kg', 'liters')", max_length=20)),
                ('type', models.CharField(choices=[('RAW', 'Raw Material'), ('PRODUCT', 'Finished Product'), ('PACKAGE', 'Package')], default='RAW', help_text='Type of item - cannot be changed once set', max_length=20)),
                ('note', models.TextField(blank=True, default='', help_text='Additional notes about the item')),
                ('category', models.ForeignKey(blank=True, help_text='Category this item belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='catalog.category')),
                ('created_by', models.ForeignKey(help_text='User who created this record', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(help_text='User who last updated this record', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Item SKU',
                'verbose_name_plural': 'Item SKUs',
                'db_table': 'catalog_itemsku',
                'ordering': ['-created_at'],
            },
            bases=(common.mixins.validatable.ValidatableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('version', models.PositiveIntegerField(default=1, help_text='Version number for optimistic locking')),
                ('image', models.ImageField(help_text='Image file for the item', upload_to=catalog.models.image.upload_item_image_path)),
                ('caption', models.CharField(blank=True, default='', help_text='Optional caption for the image', max_length=255)),
                ('is_primary', models.BooleanField(default=False, help_text='Mark as primary image for the item')),
                ('created_by', models.ForeignKey(help_text='User who created this record', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(help_text='User who last updated this record', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(help_text='The item this image belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.itemsku')),
            ],
            options={
                'verbose_name': 'Item Image',
                'verbose_name_plural': 'Item Images',
                'db_table': 'catalog_itemimage',
                'ordering': ['-is_primary', '-created_at'],
            },
            bases=(common.mixins.validatable.ValidatableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalItemImage',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, help_text='Timestamp when record was last updated')),
                ('version', models.PositiveIntegerField(default=1, help_text='Version number for optimistic locking')),
                ('image', models.TextField(help_text='Image file for the item', max_length=100)),
                ('caption', models.CharField(blank=True, default='', help_text='Optional caption for the image', max_length=255)),
                ('is_primary', models.BooleanField(default=False, help_text='Mark as primary image for the item')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(blank=True, db_constraint=False, help_text='The item this image belongs to', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalog.itemsku')),
            ],
            options={
                'verbose_name': 'historical Item Image',
                'verbose_name_plural': 'historical Item Images',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalBOM',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, help_text='Timestamp when record was last updated')),
                ('version', models.PositiveIntegerField(default=1, help_text='Version number for optimistic locking')),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Quantity of the component required', max_digits=10)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('component_sku', models.ForeignKey(blank=True, db_constraint=False, help_text='The component used in this BOM', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalog.itemsku')),
                ('parent_sku', models.ForeignKey(blank=True, db_constraint=False, help_text='The item that this BOM belongs to', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalog.itemsku')),
            ],
            options={
                'verbose_name': 'historical BOM',
                'verbose_name_plural': 'historical BOMs',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='BOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('version', models.PositiveIntegerField(default=1, help_text='Version number for optimistic locking')),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Quantity of the component required', max_digits=10)),
                ('created_by', models.ForeignKey(help_text='User who created this record', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(help_text='User who last updated this record', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('component_sku', models.ForeignKey(help_text='The component used in this BOM', on_delete=django.db.models.deletion.PROTECT, related_name='bom_component', to='catalog.itemsku')),
                ('parent_sku', models.ForeignKey(help_text='The item that this BOM belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='bom_parent', to='catalog.itemsku')),
            ],
            options={
                'verbose_name': 'BOM',
                'verbose_name_plural': 'BOMs',
                'db_table': 'catalog_bom',
                'ordering': ['-created_at'],
            },
            bases=(common.mixins.validatable.ValidatableMixin, models.Model),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['name'], name='catalog_cat_name_39f70b_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['is_active'], name='catalog_cat_is_acti_7db955_idx'),
        ),
        migrations.AddIndex(
            model_name='itemsku',
            index=models.Index(fields=['sku_code'], name='catalog_ite_sku_cod_e5dd68_idx'),
        ),
        migrations.AddIndex(
            model_name='itemsku',
            index=models.Index(fields=['type'], name='catalog_ite_type_5aa2b4_idx'),
        ),
        migrations.AddIndex(
            model_name='itemsku',
            index=models.Index(fields=['status'], name='catalog_ite_status_828b95_idx'),
        ),
        migrations.AddIndex(
            model_name='itemsku',
            index=models.Index(fields=['created_at'], name='catalog_ite_created_4ee3d9_idx'),
        ),
        migrations.AddIndex(
            model_name='itemimage',
            index=models.Index(fields=['item'], name='catalog_ite_item_id_c718d2_idx'),
        ),
        migrations.AddIndex(
            model_name='itemimage',
            index=models.Index(fields=['is_primary'], name='catalog_ite_is_prim_afebd5_idx'),
        ),
        migrations.AddIndex(
            model_name='itemimage',
            index=models.Index(fields=['created_at'], name='catalog_ite_created_78f375_idx'),
        ),
        migrations.AddIndex(
            model_name='bom',
            index=models.Index(fields=['parent_sku'], name='catalog_bom_parent__7484e0_idx'),
        ),
        migrations.AddIndex(
            model_name='bom',
            index=models.Index(fields=['component_sku'], name='catalog_bom_compone_f3dd56_idx'),
        ),
        migrations.AddIndex(
            model_name='bom',
            index=models.Index(fields=['created_at'], name='catalog_bom_created_807bdf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bom',
            unique_together={('parent_sku', 'component_sku')},
        ),
    ]
