# Generated by Django 5.2.3 on 2025-06-19 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemsku',
            name='image',
        ),
    ]
