# Generated by Django 5.2.3 on 2025-07-17 08:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalitemsku',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Item SKU', 'verbose_name_plural': 'historical Item SKUs'},
        ),
        migrations.AlterModelOptions(
            name='itemsku',
            options={'ordering': ['-created_at'], 'verbose_name': 'Item SKU', 'verbose_name_plural': 'Item SKUs'},
        ),
        migrations.RemoveField(
            model_name='historicalitemsku',
            name='description',
        ),
        migrations.RemoveField(
            model_name='historicalitemsku',
            name='is_bom_locked',
        ),
        migrations.RemoveField(
            model_name='itemsku',
            name='description',
        ),
        migrations.RemoveField(
            model_name='itemsku',
            name='is_bom_locked',
        ),
        migrations.AddField(
            model_name='historicalitemsku',
            name='note',
            field=models.TextField(blank=True, default='', help_text='Additional notes about the item'),
        ),
        migrations.AddField(
            model_name='itemsku',
            name='note',
            field=models.TextField(blank=True, default='', help_text='Additional notes about the item'),
        ),
        migrations.AlterField(
            model_name='historicalitemsku',
            name='category',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Category this item belongs to', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalog.category'),
        ),
        migrations.AlterField(
            model_name='historicalitemsku',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='User who created this item', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalitemsku',
            name='name',
            field=models.CharField(help_text='Display name for the item', max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalitemsku',
            name='sku_code',
            field=models.CharField(db_index=True, help_text='Unique identifier for the item', max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalitemsku',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('DRAFT', 'Draft')], default='ACTIVE', help_text='Current status of the item - DRAFT allows BOM structure changes, ACTIVE/INACTIVE locks BOM structure', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalitemsku',
            name='type',
            field=models.CharField(choices=[('RAW', 'Raw Material'), ('PRODUCT', 'Finished Product'), ('PACKAGE', 'Package')], default='RAW', help_text='Type of item - cannot be changed once set', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalitemsku',
            name='unit',
            field=models.CharField(help_text="Unit of measurement (e.g., 'pcs', 'kg', 'liters')", max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalitemsku',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='User who last updated this item', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalitemsku',
            name='version',
            field=models.PositiveIntegerField(default=0, help_text='Version number for optimistic locking'),
        ),
        migrations.AlterField(
            model_name='itemsku',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Category this item belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='catalog.category'),
        ),
        migrations.AlterField(
            model_name='itemsku',
            name='created_by',
            field=models.ForeignKey(help_text='User who created this item', on_delete=django.db.models.deletion.PROTECT, related_name='items_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='itemsku',
            name='name',
            field=models.CharField(help_text='Display name for the item', max_length=100),
        ),
        migrations.AlterField(
            model_name='itemsku',
            name='sku_code',
            field=models.CharField(help_text='Unique identifier for the item', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='itemsku',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('DRAFT', 'Draft')], default='ACTIVE', help_text='Current status of the item - DRAFT allows BOM structure changes, ACTIVE/INACTIVE locks BOM structure', max_length=20),
        ),
        migrations.AlterField(
            model_name='itemsku',
            name='type',
            field=models.CharField(choices=[('RAW', 'Raw Material'), ('PRODUCT', 'Finished Product'), ('PACKAGE', 'Package')], default='RAW', help_text='Type of item - cannot be changed once set', max_length=20),
        ),
        migrations.AlterField(
            model_name='itemsku',
            name='unit',
            field=models.CharField(help_text="Unit of measurement (e.g., 'pcs', 'kg', 'liters')", max_length=20),
        ),
        migrations.AlterField(
            model_name='itemsku',
            name='updated_by',
            field=models.ForeignKey(help_text='User who last updated this item', on_delete=django.db.models.deletion.PROTECT, related_name='items_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='itemsku',
            name='version',
            field=models.PositiveIntegerField(default=0, help_text='Version number for optimistic locking'),
        ),
        migrations.AddIndex(
            model_name='itemsku',
            index=models.Index(fields=['sku_code'], name='catalog_ite_sku_cod_e5dd68_idx'),
        ),
        migrations.AddIndex(
            model_name='itemsku',
            index=models.Index(fields=['type'], name='catalog_ite_type_5aa2b4_idx'),
        ),
        migrations.AddIndex(
            model_name='itemsku',
            index=models.Index(fields=['status'], name='catalog_ite_status_828b95_idx'),
        ),
        migrations.AddIndex(
            model_name='itemsku',
            index=models.Index(fields=['created_at'], name='catalog_ite_created_4ee3d9_idx'),
        ),
        migrations.AlterModelTable(
            name='itemsku',
            table='catalog_itemsku',
        ),
    ]
