# Generated by Django 5.2.3 on 2025-09-24 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalitemsku',
            name='type',
            field=models.CharField(choices=[('RAW', 'Raw Material'), ('PRODUCT', 'Finished Product')], default='RAW', help_text='Type of item - cannot be changed once set', max_length=20),
        ),
        migrations.AlterField(
            model_name='itemsku',
            name='type',
            field=models.CharField(choices=[('RAW', 'Raw Material'), ('PRODUCT', 'Finished Product')], default='RAW', help_text='Type of item - cannot be changed once set', max_length=20),
        ),
    ]
