# Generated by Django 5.2.3 on 2025-07-18 07:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_historicalitemsku_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bom',
            options={'ordering': ['parent_sku__sku_code', 'component_sku__sku_code'], 'verbose_name': 'Bill of Materials', 'verbose_name_plural': 'Bills of Materials'},
        ),
        migrations.AlterModelOptions(
            name='historicalbom',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Bill of Materials', 'verbose_name_plural': 'historical Bills of Materials'},
        ),
        migrations.AlterField(
            model_name='bom',
            name='component_sku',
            field=models.ForeignKey(help_text='Component item used in the parent', on_delete=django.db.models.deletion.PROTECT, related_name='bom_component', to='catalog.itemsku'),
        ),
        migrations.AlterField(
            model_name='bom',
            name='created_by',
            field=models.ForeignKey(help_text='User who created this BOM entry', on_delete=django.db.models.deletion.PROTECT, related_name='bom_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bom',
            name='parent_sku',
            field=models.ForeignKey(help_text='Parent item that contains the components', on_delete=django.db.models.deletion.CASCADE, related_name='bom_parent', to='catalog.itemsku'),
        ),
        migrations.AlterField(
            model_name='bom',
            name='quantity',
            field=models.DecimalField(decimal_places=2, help_text='Quantity of component needed for one unit of parent', max_digits=10),
        ),
        migrations.AlterField(
            model_name='bom',
            name='updated_by',
            field=models.ForeignKey(help_text='User who last updated this BOM entry', on_delete=django.db.models.deletion.PROTECT, related_name='bom_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bom',
            name='version',
            field=models.PositiveIntegerField(default=0, help_text='Version number for optimistic locking'),
        ),
        migrations.AlterField(
            model_name='historicalbom',
            name='component_sku',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Component item used in the parent', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalog.itemsku'),
        ),
        migrations.AlterField(
            model_name='historicalbom',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='User who created this BOM entry', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalbom',
            name='parent_sku',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Parent item that contains the components', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalog.itemsku'),
        ),
        migrations.AlterField(
            model_name='historicalbom',
            name='quantity',
            field=models.DecimalField(decimal_places=2, help_text='Quantity of component needed for one unit of parent', max_digits=10),
        ),
        migrations.AlterField(
            model_name='historicalbom',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='User who last updated this BOM entry', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalbom',
            name='version',
            field=models.PositiveIntegerField(default=0, help_text='Version number for optimistic locking'),
        ),
        migrations.AlterUniqueTogether(
            name='bom',
            unique_together={('parent_sku', 'component_sku')},
        ),
        migrations.AddIndex(
            model_name='bom',
            index=models.Index(fields=['parent_sku'], name='catalog_bom_parent__7484e0_idx'),
        ),
        migrations.AddIndex(
            model_name='bom',
            index=models.Index(fields=['component_sku'], name='catalog_bom_compone_f3dd56_idx'),
        ),
        migrations.AddIndex(
            model_name='bom',
            index=models.Index(fields=['created_at'], name='catalog_bom_created_807bdf_idx'),
        ),
        migrations.AlterModelTable(
            name='bom',
            table='catalog_bom',
        ),
    ]
