# Generated by Django 5.2.3 on 2025-07-30 05:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_bom_options_alter_historicalbom_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bom',
            options={'verbose_name': 'BOM', 'verbose_name_plural': 'BOMs'},
        ),
        migrations.AlterModelOptions(
            name='historicalbom',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical BOM', 'verbose_name_plural': 'historical BOMs'},
        ),
        migrations.AlterField(
            model_name='bom',
            name='component_sku',
            field=models.ForeignKey(help_text='The component used in this BOM', on_delete=django.db.models.deletion.PROTECT, related_name='bom_component', to='catalog.itemsku'),
        ),
        migrations.AlterField(
            model_name='bom',
            name='created_by',
            field=models.ForeignKey(help_text='User who created this BOM', on_delete=django.db.models.deletion.PROTECT, related_name='bom_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bom',
            name='parent_sku',
            field=models.ForeignKey(help_text='The item that this BOM belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='bom_parent', to='catalog.itemsku'),
        ),
        migrations.AlterField(
            model_name='bom',
            name='quantity',
            field=models.DecimalField(decimal_places=2, help_text='Quantity of the component required', max_digits=10),
        ),
        migrations.AlterField(
            model_name='bom',
            name='updated_by',
            field=models.ForeignKey(help_text='User who last updated this BOM', on_delete=django.db.models.deletion.PROTECT, related_name='bom_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalbom',
            name='component_sku',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The component used in this BOM', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalog.itemsku'),
        ),
        migrations.AlterField(
            model_name='historicalbom',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='User who created this BOM', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalbom',
            name='parent_sku',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The item that this BOM belongs to', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalog.itemsku'),
        ),
        migrations.AlterField(
            model_name='historicalbom',
            name='quantity',
            field=models.DecimalField(decimal_places=2, help_text='Quantity of the component required', max_digits=10),
        ),
        migrations.AlterField(
            model_name='historicalbom',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='User who last updated this BOM', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
