# Generated by Django 5.2.3 on 2025-08-02 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_create_stock_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when record was created'),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_by',
            field=models.ForeignKey(help_text='User who created this record', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this record is active and can be used'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Category display name', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='note',
            field=models.TextField(blank=True, default='', help_text='Optional note about the category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated'),
        ),
        migrations.AlterField(
            model_name='category',
            name='updated_by',
            field=models.ForeignKey(help_text='User who last updated this record', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='category',
            name='version',
            field=models.PositiveIntegerField(default=1, help_text='Version number for optimistic locking'),
        ),
        migrations.AlterField(
            model_name='historicalcategory',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp when record was created'),
        ),
        migrations.AlterField(
            model_name='historicalcategory',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalcategory',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this record is active and can be used'),
        ),
        migrations.AlterField(
            model_name='historicalcategory',
            name='name',
            field=models.CharField(db_index=True, help_text='Category display name', max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalcategory',
            name='note',
            field=models.TextField(blank=True, default='', help_text='Optional note about the category'),
        ),
        migrations.AlterField(
            model_name='historicalcategory',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp when record was last updated'),
        ),
        migrations.AlterField(
            model_name='historicalcategory',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalcategory',
            name='version',
            field=models.PositiveIntegerField(default=1, help_text='Version number for optimistic locking'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['name'], name='catalog_cat_name_39f70b_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['is_active'], name='catalog_cat_is_acti_7db955_idx'),
        ),
    ]
