# Generated by Django 5.2.3 on 2025-08-11 08:26

import catalog.models.image
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_historicalitemimage_itemimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemimage',
            name='image',
            field=models.ImageField(help_text='Image file for the item', upload_to=catalog.models.image.upload_item_image_path),
        ),
    ]
