# Generated by Django 5.2.3 on 2025-08-15 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_itemimage_image'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='itemimage',
            name='unique_primary_image_per_item',
        ),
    ]
